/**
 * FilmFinder — Локальная резервная база популярных фильмов
 */
window.FILMS_DATA = [
    {
        id: 278,
        title: "The Shawshank Redemption",
        titleRu: "Побег из Шоушенка",
        year: 1994,
        runtime: "2 ч 22 мин",
        genres: ["Драма", "Криминал"],
        country: "США",
        imdbRating: 9.3,
        kpRating: 9.1,
        avgRating: 9.2,
        description: "Бухгалтер Энди Дюфрейн обвинён в убийстве собственной жены и её любовника. Оказавшись в тюрьме Шоушенк, он сталкивается с жестокостью и беззаконием, но сохраняет надежду и разрабатывает невероятный план.",
        poster: "https://image.tmdb.org/t/p/w500/9cqN0KiAdb75ae317gNaEGFpNs6.jpg",
        imdbUrl: "https://www.imdb.com/title/tt0111161/",
        kpUrl: "https://www.kinopoisk.ru/film/326/",
        status: "Вышел"
    },
    {
        id: 238,
        title: "The Godfather",
        titleRu: "Крёстный отец",
        year: 1972,
        runtime: "2 ч 55 мин",
        genres: ["Драма", "Криминал"],
        country: "США",
        imdbRating: 9.2,
        kpRating: 8.7,
        avgRating: 9.0,
        description: "Криминальная сага о сицилийском мафиозном клане Корлеоне в Нью-Йорке. Глава семьи дон Вито Корлеоне выдаёт замуж дочь, пока его младший сын Майкл возвращается с войны и постепенно входит в семейный бизнес.",
        poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        imdbUrl: "https://www.imdb.com/title/tt0068646/",
        kpUrl: "https://www.kinopoisk.ru/film/325/",
        status: "Вышел"
    },
    {
        id: 155,
        title: "The Dark Knight",
        titleRu: "Тёмный рыцарь",
        year: 2008,
        runtime: "2 ч 32 мин",
        genres: ["Боевик", "Криминал", "Драма", "Триллер"],
        country: "США",
        imdbRating: 9.0,
        kpRating: 8.5,
        avgRating: 8.8,
        description: "Бэтмен поднимает ставки в войне с криминалом. С помощью лейтенанта Джима Гордона и прокурора Харви Дента он намерен очистить улицы Готэма, но в городе появляется гений хаоса — Джокер.",
        poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        imdbUrl: "https://www.imdb.com/title/tt0468569/",
        kpUrl: "https://www.kinopoisk.ru/film/111543/",
        status: "Вышел"
    },
    {
        id: 27205,
        title: "Inception",
        titleRu: "Начало",
        year: 2010,
        runtime: "2 ч 28 мин",
        genres: ["Боевик", "Научная фантастика", "Приключения"],
        country: "США",
        imdbRating: 8.8,
        kpRating: 8.7,
        avgRating: 8.8,
        description: "Дом Кобб — искусный вор, лучший в опасном искусстве извлечения ценных секретов из глубин подсознания во время сна. Ему предстоит совершить невозможное: не украсть мысль, а внедрить её.",
        poster: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
        imdbUrl: "https://www.imdb.com/title/tt1375666/",
        kpUrl: "https://www.kinopoisk.ru/film/447301/",
        status: "Вышел"
    },
    {
        id: 157336,
        title: "Interstellar",
        titleRu: "Интерстеллар",
        year: 2014,
        runtime: "2 ч 49 мин",
        genres: ["Научная фантастика", "Драма", "Приключения"],
        country: "США",
        imdbRating: 8.7,
        kpRating: 8.6,
        avgRating: 8.7,
        description: "Когда засуха и пыльные бури приводят человечество к продовольственному кризису, коллектив исследователей отправляется сквозь червоточину в поисках новой пригодной для жизни планеты.",
        poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        imdbUrl: "https://www.imdb.com/title/tt0816692/",
        kpUrl: "https://www.kinopoisk.ru/film/258687/",
        status: "Вышел"
    },
    {
        id: 550,
        title: "Fight Club",
        titleRu: "Бойцовский клуб",
        year: 1999,
        runtime: "2 ч 19 мин",
        genres: ["Драма", "Триллер"],
        country: "США",
        imdbRating: 8.8,
        kpRating: 8.7,
        avgRating: 8.8,
        description: "Сотрудник страховой компании, страдающий бессонницей, встречает харизматичного торговца мылом Тайлера Дёрдена с извращённой философией саморазрушения. Вместе они основывают тайный Бойцовский клуб.",
        poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
        imdbUrl: "https://www.imdb.com/title/tt0137523/",
        kpUrl: "https://www.kinopoisk.ru/film/361/",
        status: "Вышел"
    },
    {
        id: 680,
        title: "Pulp Fiction",
        titleRu: "Криминальное чтиво",
        year: 1994,
        runtime: "2 ч 34 мин",
        genres: ["Триллер", "Криминал"],
        country: "США",
        imdbRating: 8.9,
        kpRating: 8.6,
        avgRating: 8.8,
        description: "Двое бандитов Винсент Вега и Джулс Виннфилд ведут философские беседы в перерывах между разборками и выполнением поручений криминального босса Марселласа Уоллеса.",
        poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        imdbUrl: "https://www.imdb.com/title/tt0110912/",
        kpUrl: "https://www.kinopoisk.ru/film/342/",
        status: "Вышел"
    },
    {
        id: 122,
        title: "The Lord of the Rings: The Return of the King",
        titleRu: "Властелин колец: Возвращение Короля",
        year: 2003,
        runtime: "3 ч 21 мин",
        genres: ["Приключения", "Фэнтези", "Боевик"],
        country: "Новая Зеландия",
        imdbRating: 9.0,
        kpRating: 8.7,
        avgRating: 8.9,
        description: "Повелитель сил тьмы Саурон направляет свои бесчисленные полчища под стены Минас-Тирита. В это время Фродо и Сэм приближаются к Роковой горе, чтобы уничтожить Кольцо Всевластья.",
        poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
        imdbUrl: "https://www.imdb.com/title/tt0167260/",
        kpUrl: "https://www.kinopoisk.ru/film/3498/",
        status: "Вышел"
    }
];
