window.SERIES_DATA = [
  {
    "id": 1,
    "title": "Breaking Bad",
    "titleRu": "Во все тяжкие",
    "year": 2008,
    "endYear": 2013,
    "seasons": 5,
    "episodes": 62,
    "genres": [
      "Драма",
      "Криминал",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 9.5,
    "kpRating": 8.9,
    "avgRating": 9.2,
    "description": "Школьный учитель химии Уолтер Уайт узнаёт, что болен неоперабельным раком лёгких. Чтобы обеспечить будущее своей семьи, он начинает производить и продавать метамфетамин.",
    "poster": "https://image.tmdb.org/t/p/w500/gwB6E7Zi5L3J9WA2y0zLeKuc3ul.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0903747/",
    "kpUrl": "https://www.kinopoisk.ru/series/404900/",
    "status": "Завершён"
  },
  {
    "id": 2,
    "title": "Game of Thrones",
    "titleRu": "Игра престолов",
    "year": 2011,
    "endYear": 2019,
    "seasons": 8,
    "episodes": 73,
    "genres": [
      "Фэнтези",
      "Драма",
      "Боевик",
      "Приключения"
    ],
    "country": "США",
    "imdbRating": 9.2,
    "kpRating": 9,
    "avgRating": 9.1,
    "description": "Несколько благородных семей борются за контроль над Железным троном Вестероса, в то время как древнее зло пробуждается на Севере. Эпическая сага о власти, предательстве и драконах.",
    "poster": "https://image.tmdb.org/t/p/w500/1sIAsLSaMwm3mb7Y6jISMv56McR.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0944947/",
    "kpUrl": "https://www.kinopoisk.ru/series/464963/",
    "status": "Завершён"
  },
  {
    "id": 3,
    "title": "The Wire",
    "titleRu": "Прослушка",
    "year": 2002,
    "endYear": 2008,
    "seasons": 5,
    "episodes": 60,
    "genres": [
      "Криминал",
      "Драма",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 9.3,
    "kpRating": 8.5,
    "avgRating": 8.9,
    "description": "Детальный взгляд на преступную жизнь Балтимора глазами как полицейских, так и самих преступников. Каждый сезон раскрывает новую грань жизни города.",
    "poster": "https://image.tmdb.org/t/p/w500/aoy6XphJtLvCfVmLFqBLaR56BAW.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0279461/",
    "kpUrl": "https://www.kinopoisk.ru/series/402955/",
    "status": "Завершён"
  },
  {
    "id": 4,
    "title": "The Sopranos",
    "titleRu": "Клан Сопрано",
    "year": 1999,
    "endYear": 2007,
    "seasons": 6,
    "episodes": 86,
    "genres": [
      "Криминал",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 9.2,
    "kpRating": 8.8,
    "avgRating": 9,
    "description": "Босс мафии из Нью-Джерси Тони Сопрано пытается найти баланс между своей семейной жизнью и криминальной деятельностью. Из-за панических атак он тайно посещает психиатра.",
    "poster": "https://image.tmdb.org/t/p/w500/l7kBNxisz66jJApaa82WxqjtKbb.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0141842/",
    "kpUrl": "https://www.kinopoisk.ru/series/77044/",
    "status": "Завершён"
  },
  {
    "id": 5,
    "title": "Friends",
    "titleRu": "Друзья",
    "year": 1994,
    "endYear": 2004,
    "seasons": 10,
    "episodes": 236,
    "genres": [
      "Комедия",
      "Мелодрама"
    ],
    "country": "США",
    "imdbRating": 8.9,
    "kpRating": 9.2,
    "avgRating": 9.1,
    "description": "Шестеро друзей живут в Нью-Йорке, делятся своими радостями и горестями, строят карьеру и ищут любовь. Культовый ситком, ставший классикой телевидения.",
    "poster": "https://image.tmdb.org/t/p/w500/zBOs8S3UOHyWLzOl9gF8lknBxlL.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0108778/",
    "kpUrl": "https://www.kinopoisk.ru/series/77044/",
    "status": "Завершён"
  },
  {
    "id": 6,
    "title": "The Office",
    "titleRu": "Офис",
    "year": 2005,
    "endYear": 2013,
    "seasons": 9,
    "episodes": 201,
    "genres": [
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 9,
    "kpRating": 8.6,
    "avgRating": 8.8,
    "description": "Псевдодокументальный сериал о повседневной жизни сотрудников филиала бумажной компании Dunder Mifflin в Скрантоне. Ими руководит нелепый, но добродушный босс Майкл Скотт.",
    "poster": "https://image.tmdb.org/t/p/w500/zjW7g5PGsJMy7pIr0hKdBKWcH9V.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0386676/",
    "kpUrl": "https://www.kinopoisk.ru/series/253254/",
    "status": "Завершён"
  },
  {
    "id": 7,
    "title": "Stranger Things",
    "titleRu": "Очень странные дела",
    "year": 2016,
    "endYear": null,
    "seasons": 4,
    "episodes": 34,
    "genres": [
      "Фантастика",
      "Ужасы",
      "Триллер",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.7,
    "kpRating": 8.5,
    "avgRating": 8.6,
    "description": "В тихом городке пропадает мальчик, и его друзья начинают собственное расследование. Они сталкиваются с правительственными тайнами и сверхъестественными силами.",
    "poster": "https://image.tmdb.org/t/p/w500/nW3cral1e2r3xfLySPE1U9bailS.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt4574334/",
    "kpUrl": "https://www.kinopoisk.ru/series/915196/",
    "status": "Выходит"
  },
  {
    "id": 8,
    "title": "Better Call Saul",
    "titleRu": "Лучше звоните Солу",
    "year": 2015,
    "endYear": 2022,
    "seasons": 6,
    "episodes": 63,
    "genres": [
      "Драма",
      "Криминал"
    ],
    "country": "США",
    "imdbRating": 9,
    "kpRating": 8.3,
    "avgRating": 8.7,
    "description": "Приквел сериала «Во все тяжкие». История превращения мелкого адвоката Джимми Макгилла в беспринципного криминального юриста Сола Гудмана.",
    "poster": "https://image.tmdb.org/t/p/w500/o2jgxiP6PNaZQzlql8DgouwTBvz.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt3032476/",
    "kpUrl": "https://www.kinopoisk.ru/series/803154/",
    "status": "Завершён"
  },
  {
    "id": 9,
    "title": "True Detective",
    "titleRu": "Настоящий детектив",
    "year": 2014,
    "endYear": null,
    "seasons": 4,
    "episodes": 30,
    "genres": [
      "Детектив",
      "Криминал",
      "Драма",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 8.9,
    "kpRating": 8.7,
    "avgRating": 8.8,
    "description": "Антология о расследованиях запутанных и мрачных преступлений. Каждый сезон представляет новую историю, новых персонажей и разные локации.",
    "poster": "https://image.tmdb.org/t/p/w500/dHqKLovbM9GT0fkwtL5ew5SPtmk.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2356777/",
    "kpUrl": "https://www.kinopoisk.ru/series/681831/",
    "status": "Выходит"
  },
  {
    "id": 10,
    "title": "Fargo",
    "titleRu": "Фарго",
    "year": 2014,
    "endYear": null,
    "seasons": 5,
    "episodes": 51,
    "genres": [
      "Криминал",
      "Триллер",
      "Драма",
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.9,
    "kpRating": 8.4,
    "avgRating": 8.7,
    "description": "Криминальная антология, вдохновленная одноимённым фильмом братьев Коэн. В каждом сезоне — своя абсурдная и кровавая история, происходящая на заснеженном Среднем Западе.",
    "poster": "https://image.tmdb.org/t/p/w500/r8HpRhKl5q0kiNehdjVOmTC7K7p.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2802850/",
    "kpUrl": "https://www.kinopoisk.ru/series/767379/",
    "status": "Выходит"
  },
  {
    "id": 11,
    "title": "The Mandalorian",
    "titleRu": "Мандалорец",
    "year": 2019,
    "endYear": null,
    "seasons": 3,
    "episodes": 24,
    "genres": [
      "Фантастика",
      "Боевик",
      "Приключения"
    ],
    "country": "США",
    "imdbRating": 8.7,
    "kpRating": 8.1,
    "avgRating": 8.4,
    "description": "Одинокий наёмник живёт на краю обитаемой галактики. Его жизнь меняется, когда он берёт заказ на доставку загадочного ребёнка, обладающего огромной силой.",
    "poster": "https://image.tmdb.org/t/p/w500/3JcJfU9wm6sA2R6LQtnsBJsHMmY.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt8111088/",
    "kpUrl": "https://www.kinopoisk.ru/series/1199773/",
    "status": "Выходит"
  },
  {
    "id": 12,
    "title": "House of the Dragon",
    "titleRu": "Дом Дракона",
    "year": 2022,
    "endYear": null,
    "seasons": 2,
    "episodes": 18,
    "genres": [
      "Фэнтези",
      "Драма",
      "Боевик"
    ],
    "country": "США",
    "imdbRating": 8.4,
    "kpRating": 8.1,
    "avgRating": 8.3,
    "description": "Приквел «Игры престолов», рассказывающий о падении дома Таргариенов. История гражданской войны, известной как «Танец Драконов».",
    "poster": "https://image.tmdb.org/t/p/w500/hXyYN6LFo7QnKUA3QBx7B3KsnJE.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt11198330/",
    "kpUrl": "https://www.kinopoisk.ru/series/1316601/",
    "status": "Выходит"
  },
  {
    "id": 13,
    "title": "The Last of Us",
    "titleRu": "Одни из нас",
    "year": 2023,
    "endYear": null,
    "seasons": 1,
    "episodes": 9,
    "genres": [
      "Фантастика",
      "Драма",
      "Боевик",
      "Ужасы"
    ],
    "country": "США",
    "imdbRating": 8.8,
    "kpRating": 8,
    "avgRating": 8.4,
    "description": "В постапокалиптическом мире контрабандист Джоэл должен провести девочку Элли через опасные территории. Она может стать ключом к спасению человечества от грибковой инфекции.",
    "poster": "https://image.tmdb.org/t/p/w500/69loIrm9JPpPRE3Akw4yRoitSYn.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt3581920/",
    "kpUrl": "https://www.kinopoisk.ru/series/1356784/",
    "status": "Выходит"
  },
  {
    "id": 14,
    "title": "Severance",
    "titleRu": "Разделение",
    "year": 2022,
    "endYear": null,
    "seasons": 1,
    "episodes": 9,
    "genres": [
      "Триллер",
      "Драма",
      "Фантастика",
      "Детектив"
    ],
    "country": "США",
    "imdbRating": 8.7,
    "kpRating": 8.3,
    "avgRating": 8.5,
    "description": "Сотрудники корпорации Lumon соглашаются на процедуру разделения, которая отделяет их рабочие воспоминания от личных. Однако всё оказывается не так просто.",
    "poster": "https://image.tmdb.org/t/p/w500/Ag7gBPnh8Cpn5xvCdPPA4RJRN1L.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt11280740/",
    "kpUrl": "https://www.kinopoisk.ru/series/1330691/",
    "status": "Выходит"
  },
  {
    "id": 15,
    "title": "The Bear",
    "titleRu": "Медведь",
    "year": 2022,
    "endYear": null,
    "seasons": 3,
    "episodes": 28,
    "genres": [
      "Драма",
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.6,
    "kpRating": 7.9,
    "avgRating": 8.3,
    "description": "Молодой шеф-повар из мира высокой кухни возвращается в Чикаго, чтобы управлять семейной закусочной после смерти брата. Он сталкивается с долгами, упрямым персоналом и личными демонами.",
    "poster": "https://image.tmdb.org/t/p/w500/moFSxli4RPhKtCU26WyW6tJj0Vm.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt14452776/",
    "kpUrl": "https://www.kinopoisk.ru/series/4887372/",
    "status": "Выходит"
  },
  {
    "id": 16,
    "title": "Succession",
    "titleRu": "Наследники",
    "year": 2018,
    "endYear": 2023,
    "seasons": 4,
    "episodes": 39,
    "genres": [
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.9,
    "kpRating": 8.2,
    "avgRating": 8.6,
    "description": "Семья Рой владеет одним из крупнейших медиаконгломератов в мире. Когда здоровье патриарха Логана Роя ухудшается, его дети начинают безжалостную борьбу за власть.",
    "poster": "https://image.tmdb.org/t/p/w500/5vZjUwl2NxNJY2cH7e8tmXdIjBA.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt7660850/",
    "kpUrl": "https://www.kinopoisk.ru/series/1043813/",
    "status": "Завершён"
  },
  {
    "id": 17,
    "title": "Ted Lasso",
    "titleRu": "Тед Лассо",
    "year": 2020,
    "endYear": 2023,
    "seasons": 3,
    "episodes": 34,
    "genres": [
      "Комедия",
      "Драма",
      "Спорт"
    ],
    "country": "США",
    "imdbRating": 8.8,
    "kpRating": 8.3,
    "avgRating": 8.6,
    "description": "Американского тренера по американскому футболу нанимают тренировать английский футбольный клуб. Несмотря на отсутствие опыта, он завоёвывает сердца игроков своим неиссякаемым оптимизмом.",
    "poster": "https://image.tmdb.org/t/p/w500/gO2kQUDfZWsvdDetUljaTI6t87i.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt10986410/",
    "kpUrl": "https://www.kinopoisk.ru/series/1318991/",
    "status": "Завершён"
  },
  {
    "id": 18,
    "title": "Ozark",
    "titleRu": "Озарк",
    "year": 2017,
    "endYear": 2022,
    "seasons": 4,
    "episodes": 44,
    "genres": [
      "Криминал",
      "Драма",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 8.5,
    "kpRating": 7.9,
    "avgRating": 8.2,
    "description": "Финансовый консультант Марти Бёрд перевозит семью в курортный городок Озарк. Ему нужно отмыть огромную сумму денег для мексиканского наркокартеля.",
    "poster": "https://image.tmdb.org/t/p/w500/uRvsisd0e9vLtJyGWz9GSptVRW4.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt5071412/",
    "kpUrl": "https://www.kinopoisk.ru/series/969854/",
    "status": "Завершён"
  },
  {
    "id": 19,
    "title": "Mindhunter",
    "titleRu": "Охотник за разумом",
    "year": 2017,
    "endYear": 2019,
    "seasons": 2,
    "episodes": 19,
    "genres": [
      "Триллер",
      "Криминал",
      "Детектив",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.6,
    "kpRating": 8.1,
    "avgRating": 8.4,
    "description": "Агенты ФБР в конце 1970-х годов начинают опрашивать серийных убийц, чтобы понять их психологию. Эти исследования закладывают основу для современного криминального профилирования.",
    "poster": "https://image.tmdb.org/t/p/w500/tEBOVb1ZGT5XapLn5YLXk3Msr8N.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt5290382/",
    "kpUrl": "https://www.kinopoisk.ru/series/968984/",
    "status": "Завершён"
  },
  {
    "id": 20,
    "title": "Narcos",
    "titleRu": "Нарко",
    "year": 2015,
    "endYear": 2017,
    "seasons": 3,
    "episodes": 30,
    "genres": [
      "Криминал",
      "Драма",
      "Биография"
    ],
    "country": "США",
    "imdbRating": 8.8,
    "kpRating": 8.4,
    "avgRating": 8.6,
    "description": "Хроника криминальной жизни колумбийского наркобарона Пабло Эскобара. История противостояния картеля и агентов УБН.",
    "poster": "https://image.tmdb.org/t/p/w500/51et4U2FGR7eEroNrAxdL3nSP0O.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2707408/",
    "kpUrl": "https://www.kinopoisk.ru/series/820638/",
    "status": "Завершён"
  },
  {
    "id": 21,
    "title": "Black Mirror",
    "titleRu": "Чёрное зеркало",
    "year": 2011,
    "endYear": null,
    "seasons": 6,
    "episodes": 27,
    "genres": [
      "Фантастика",
      "Триллер",
      "Драма"
    ],
    "country": "Великобритания",
    "imdbRating": 8.7,
    "kpRating": 8.5,
    "avgRating": 8.6,
    "description": "Научно-фантастическая антология, исследующая тёмную сторону технологий и их влияние на современное общество. Каждая серия — отдельная антиутопическая история.",
    "poster": "https://image.tmdb.org/t/p/w500/usjxU1cyXk9FDVCJFwIT01iCLty.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2085059/",
    "kpUrl": "https://www.kinopoisk.ru/series/655800/",
    "status": "Выходит"
  },
  {
    "id": 22,
    "title": "Peaky Blinders",
    "titleRu": "Острые козырьки",
    "year": 2013,
    "endYear": 2022,
    "seasons": 6,
    "episodes": 36,
    "genres": [
      "Криминал",
      "Драма"
    ],
    "country": "Великобритания",
    "imdbRating": 8.8,
    "kpRating": 8.4,
    "avgRating": 8.6,
    "description": "Британский криминальный сериал о преступном клане Шелби в Бирмингеме после Первой мировой войны. Семья пытается расширить своё влияние и легализовать бизнес.",
    "poster": "https://image.tmdb.org/t/p/w500/pVJzfWgb3sHN29hLaiI5jmBN9vx.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2442560/",
    "kpUrl": "https://www.kinopoisk.ru/series/716587/",
    "status": "Завершён"
  },
  {
    "id": 23,
    "title": "Sherlock",
    "titleRu": "Шерлок",
    "year": 2010,
    "endYear": 2017,
    "seasons": 4,
    "episodes": 15,
    "genres": [
      "Детектив",
      "Триллер",
      "Криминал"
    ],
    "country": "Великобритания",
    "imdbRating": 9.1,
    "kpRating": 8.9,
    "avgRating": 9,
    "description": "Современная адаптация произведений Артура Конан Дойла. Шерлок Холмс и доктор Ватсон расследуют запутанные преступления в Лондоне XXI века.",
    "poster": "https://image.tmdb.org/t/p/w500/j1OzoewUK3fA7bjMX8oB1mwyG1P.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1475582/",
    "kpUrl": "https://www.kinopoisk.ru/series/502838/",
    "status": "Завершён"
  },
  {
    "id": 24,
    "title": "The Crown",
    "titleRu": "Корона",
    "year": 2016,
    "endYear": 2023,
    "seasons": 6,
    "episodes": 60,
    "genres": [
      "Драма",
      "Исторический",
      "Биография"
    ],
    "country": "Великобритания",
    "imdbRating": 8.6,
    "kpRating": 8.3,
    "avgRating": 8.5,
    "description": "Историческая драма, рассказывающая о правлении королевы Елизаветы II. Сериал охватывает политические интриги и личную жизнь британской королевской семьи.",
    "poster": "https://image.tmdb.org/t/p/w500/1fgswE7VWpGQPD68DUFx6KPnWWa.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt4786824/",
    "kpUrl": "https://www.kinopoisk.ru/series/934053/",
    "status": "Завершён"
  },
  {
    "id": 25,
    "title": "Downton Abbey",
    "titleRu": "Аббатство Даунтон",
    "year": 2010,
    "endYear": 2015,
    "seasons": 6,
    "episodes": 52,
    "genres": [
      "Драма",
      "Исторический",
      "Мелодрама"
    ],
    "country": "Великобритания",
    "imdbRating": 8.7,
    "kpRating": 8.4,
    "avgRating": 8.6,
    "description": "Жизнь аристократической семьи Кроули и её прислуги в пост-эдвардианскую эпоху. На фоне исторических событий разворачиваются личные драмы обитателей поместья.",
    "poster": "https://image.tmdb.org/t/p/w500/wTynUmuCh4ttvblV6CH0Efui1Wk.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1606375/",
    "kpUrl": "https://www.kinopoisk.ru/series/551213/",
    "status": "Завершён"
  },
  {
    "id": 26,
    "title": "Doctor Who",
    "titleRu": "Доктор Кто",
    "year": 2005,
    "endYear": null,
    "seasons": 14,
    "episodes": 175,
    "genres": [
      "Фантастика",
      "Приключения",
      "Драма"
    ],
    "country": "Великобритания",
    "imdbRating": 8.6,
    "kpRating": 8.1,
    "avgRating": 8.4,
    "description": "Инопланетянин, известный как Доктор, путешествует сквозь время и пространство в своём корабле ТАРДИС. Он спасает цивилизации и восстанавливает справедливость.",
    "poster": "https://image.tmdb.org/t/p/w500/4yAIKCTUumob1Xx38yuW1U9IbJe.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0436992/",
    "kpUrl": "https://www.kinopoisk.ru/series/257396/",
    "status": "Выходит"
  },
  {
    "id": 27,
    "title": "Fleabag",
    "titleRu": "Дрянь",
    "year": 2016,
    "endYear": 2019,
    "seasons": 2,
    "episodes": 12,
    "genres": [
      "Комедия",
      "Драма"
    ],
    "country": "Великобритания",
    "imdbRating": 8.7,
    "kpRating": 8.2,
    "avgRating": 8.5,
    "description": "История молодой женщины, пытающейся наладить жизнь в современном Лондоне. Она преодолевает личную трагедию с помощью чёрного юмора.",
    "poster": "https://image.tmdb.org/t/p/w500/qkk7jlUm25pcRecvMLD2IPWg8Ec.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt5687612/",
    "kpUrl": "https://www.kinopoisk.ru/series/1000627/",
    "status": "Завершён"
  },
  {
    "id": 28,
    "title": "Chernobyl",
    "titleRu": "Чернобыль",
    "year": 2019,
    "endYear": 2019,
    "seasons": 1,
    "episodes": 5,
    "genres": [
      "Драма",
      "Исторический",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 9.3,
    "kpRating": 8.8,
    "avgRating": 9.1,
    "description": "Мини-сериал, реконструирующий события аварии на Чернобыльской АЭС в 1986 году. История о героизме ликвидаторов и попытках скрыть масштабы катастрофы.",
    "poster": "https://image.tmdb.org/t/p/w500/qhzSVp06AGGcziMoibInZ5PY0Eg.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt10048342/",
    "kpUrl": "https://www.kinopoisk.ru/series/1227289/",
    "status": "Завершён"
  },
  {
    "id": 29,
    "title": "Band of Brothers",
    "titleRu": "Братья по оружию",
    "year": 2001,
    "endYear": 2001,
    "seasons": 1,
    "episodes": 10,
    "genres": [
      "Драма",
      "Исторический",
      "Боевик"
    ],
    "country": "США",
    "imdbRating": 9.4,
    "kpRating": 8.9,
    "avgRating": 9.2,
    "description": "Эпическая военная драма о боевом пути роты E парашютно-десантного полка США во время Второй мировой войны, от тренировочного лагеря до конца войны.",
    "poster": "https://image.tmdb.org/t/p/w500/3IghRHb3ZHVO6x1dRDaRyCMJxRn.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0185906/",
    "kpUrl": "https://www.kinopoisk.ru/series/77180/",
    "status": "Завершён"
  },
  {
    "id": 30,
    "title": "The Boys",
    "titleRu": "Пацаны",
    "year": 2019,
    "endYear": null,
    "seasons": 4,
    "episodes": 32,
    "genres": [
      "Фантастика",
      "Боевик",
      "Комедия",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.7,
    "kpRating": 8.3,
    "avgRating": 8.5,
    "description": "В мире, где супергерои злоупотребляют своими силами и корпоративной властью, отряд мстителей-одиночек пытается вывести их на чистую воду.",
    "poster": "https://image.tmdb.org/t/p/w500/3NqlBDpWI83TgQ9nmeFwTVxEmtZ.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1190634/",
    "kpUrl": "https://www.kinopoisk.ru/series/1049929/",
    "status": "Выходит"
  },
  {
    "id": 31,
    "title": "Invincible",
    "titleRu": "Неуязвимый",
    "year": 2021,
    "endYear": null,
    "seasons": 2,
    "episodes": 16,
    "genres": [
      "Анимация",
      "Фантастика",
      "Боевик",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.7,
    "kpRating": 8.4,
    "avgRating": 8.6,
    "description": "Сын самого могущественного супергероя на Земле открывает в себе силы. Но вскоре он узнает, что наследие его отца скрывает страшную правду.",
    "poster": "https://image.tmdb.org/t/p/w500/ucqjLgnoA5n7GAXBCju6l0RwRcr.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt6741278/",
    "kpUrl": "https://www.kinopoisk.ru/series/1199778/",
    "status": "Выходит"
  },
  {
    "id": 32,
    "title": "Wednesday",
    "titleRu": "Уэнсдэй",
    "year": 2022,
    "endYear": null,
    "seasons": 1,
    "episodes": 8,
    "genres": [
      "Фэнтези",
      "Комедия",
      "Детектив",
      "Криминал"
    ],
    "country": "США",
    "imdbRating": 8.1,
    "kpRating": 8,
    "avgRating": 8.1,
    "description": "Уэнсдэй Аддамс поступает в академию Невермор. Там ей предстоит овладеть экстрасенсорными способностями и разгадать тайну, в которую втянуты её родители.",
    "poster": "https://image.tmdb.org/t/p/w500/lx7ipUuzHmbOa1qzMPj4ypZ7A8u.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt13443470/",
    "kpUrl": "https://www.kinopoisk.ru/series/4351608/",
    "status": "Выходит"
  },
  {
    "id": 33,
    "title": "Squid Game",
    "titleRu": "Игра в кальмара",
    "year": 2021,
    "endYear": null,
    "seasons": 1,
    "episodes": 9,
    "genres": [
      "Триллер",
      "Драма",
      "Боевик"
    ],
    "country": "Южная Корея",
    "imdbRating": 8,
    "kpRating": 7.5,
    "avgRating": 7.8,
    "description": "Сотни людей, испытывающих финансовые трудности, принимают приглашение поучаствовать в тайном турнире на выживание. Приз огромен, но ставки смертельно высоки.",
    "poster": "https://image.tmdb.org/t/p/w500/6zHKgCKht3vwrtSXFvSUntSRsJh.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt10919420/",
    "kpUrl": "https://www.kinopoisk.ru/series/1309640/",
    "status": "Выходит"
  },
  {
    "id": 34,
    "title": "Dark",
    "titleRu": "Тьма",
    "year": 2017,
    "endYear": 2020,
    "seasons": 3,
    "episodes": 26,
    "genres": [
      "Фантастика",
      "Триллер",
      "Драма",
      "Детектив"
    ],
    "country": "Германия",
    "imdbRating": 8.7,
    "kpRating": 8.1,
    "avgRating": 8.4,
    "description": "Исчезновение детей в немецком городке Винден обнажает двойную жизнь и разрушенные отношения четырех семей. Сюжет охватывает несколько поколений и временных линий.",
    "poster": "https://image.tmdb.org/t/p/w500/ikhUNN25WVfMN2uvoJLLKYXp8jE.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt5753856/",
    "kpUrl": "https://www.kinopoisk.ru/series/1002088/",
    "status": "Завершён"
  },
  {
    "id": 35,
    "title": "Money Heist",
    "titleRu": "Бумажный дом",
    "year": 2017,
    "endYear": 2021,
    "seasons": 5,
    "episodes": 41,
    "genres": [
      "Криминал",
      "Триллер",
      "Драма",
      "Боевик"
    ],
    "country": "Испания",
    "imdbRating": 8.2,
    "kpRating": 8,
    "avgRating": 8.1,
    "description": "Таинственный человек по прозвищу Профессор собирает команду авантюристов для ограбления Королевского монетного двора Испании. Их план дерзок и амбициозен.",
    "poster": "https://image.tmdb.org/t/p/w500/x9YQ28gwAkAXCSw7n1cAsPbJaTF.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt6468322/",
    "kpUrl": "https://www.kinopoisk.ru/series/1046206/",
    "status": "Завершён"
  },
  {
    "id": 36,
    "title": "Lupin",
    "titleRu": "Люпен",
    "year": 2021,
    "endYear": null,
    "seasons": 3,
    "episodes": 17,
    "genres": [
      "Криминал",
      "Драма",
      "Детектив",
      "Боевик"
    ],
    "country": "Франция",
    "imdbRating": 7.5,
    "kpRating": 7.4,
    "avgRating": 7.5,
    "description": "Вдохновлённый приключениями Арсена Люпена, джентльмен-грабитель Ассан Диоп решает отомстить за несправедливость, от которой пострадал его отец.",
    "poster": "https://image.tmdb.org/t/p/w500/64Eu2KUZOFhhSmkdb3oUw124tYQ.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2531336/",
    "kpUrl": "https://www.kinopoisk.ru/series/1376822/",
    "status": "Выходит"
  },
  {
    "id": 37,
    "title": "Yellowjackets",
    "titleRu": "Шершни",
    "year": 2021,
    "endYear": null,
    "seasons": 2,
    "episodes": 19,
    "genres": [
      "Ужасы",
      "Драма",
      "Детектив",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 7.8,
    "kpRating": 7.3,
    "avgRating": 7.6,
    "description": "Женская школьная команда по футболу терпит крушение в диких лесах. Сериал показывает, как они выживали в прошлом и как эти события преследуют их в настоящем.",
    "poster": "https://image.tmdb.org/t/p/w500/bcp7zBSBNDKUOksC5mYS3F10WS5.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt10655694/",
    "kpUrl": "https://www.kinopoisk.ru/series/1302830/",
    "status": "Выходит"
  },
  {
    "id": 38,
    "title": "Lost",
    "titleRu": "Остаться в живых",
    "year": 2004,
    "endYear": 2010,
    "seasons": 6,
    "episodes": 121,
    "genres": [
      "Приключения",
      "Драма",
      "Фантастика",
      "Детектив"
    ],
    "country": "США",
    "imdbRating": 8.3,
    "kpRating": 8.1,
    "avgRating": 8.2,
    "description": "Пассажиры рейса Oceanic 815, потерпевшего крушение, оказываются на загадочном тропическом острове. Они вынуждены сотрудничать, чтобы выжить и раскрыть тайны острова.",
    "poster": "https://image.tmdb.org/t/p/w500/jR6yfKTUv7HqvyROtoRMuKzlFCb.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0411008/",
    "kpUrl": "https://www.kinopoisk.ru/series/79948/",
    "status": "Завершён"
  },
  {
    "id": 39,
    "title": "Prison Break",
    "titleRu": "Побег",
    "year": 2005,
    "endYear": 2017,
    "seasons": 5,
    "episodes": 90,
    "genres": [
      "Боевик",
      "Криминал",
      "Драма",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 8.3,
    "kpRating": 8.4,
    "avgRating": 8.4,
    "description": "Майкл Скофилд намеренно совершает преступление, чтобы попасть в тюрьму. Его цель — спасти своего брата Линкольна, приговорённого к смертной казни за убийство, которого тот не совершал.",
    "poster": "https://image.tmdb.org/t/p/w500/728jOvI7AyRfiV3Iu3ZzDBJ3Oku.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0455275/",
    "kpUrl": "https://www.kinopoisk.ru/series/258048/",
    "status": "Завершён"
  },
  {
    "id": 40,
    "title": "Dexter",
    "titleRu": "Декстер",
    "year": 2006,
    "endYear": 2013,
    "seasons": 8,
    "episodes": 96,
    "genres": [
      "Криминал",
      "Драма",
      "Детектив",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 8.6,
    "kpRating": 8.3,
    "avgRating": 8.5,
    "description": "Декстер Морган работает судмедэкспертом в полиции Майами. По ночам он — серийный убийца, который убивает только преступников, ускользнувших от правосудия.",
    "poster": "https://image.tmdb.org/t/p/w500/93dEzWiupRP0Rq8S87MzfzSHS1x.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0773262/",
    "kpUrl": "https://www.kinopoisk.ru/series/277537/",
    "status": "Завершён"
  },
  {
    "id": 41,
    "title": "House M.D.",
    "titleRu": "Доктор Хаус",
    "year": 2004,
    "endYear": 2012,
    "seasons": 8,
    "episodes": 177,
    "genres": [
      "Драма",
      "Детектив",
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.7,
    "kpRating": 8.8,
    "avgRating": 8.8,
    "description": "Эксцентричный, циничный, но гениальный врач-диагност Грегори Хаус спасает жизни пациентов, разгадывая сложные медицинские загадки. Он ненавидит общаться с людьми и борется с собственной болью.",
    "poster": "https://image.tmdb.org/t/p/w500/hXoGcvNOeWZkxbaitu7ZvEM0hQJ.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0412142/",
    "kpUrl": "https://www.kinopoisk.ru/series/178710/",
    "status": "Завершён"
  },
  {
    "id": 42,
    "title": "24",
    "titleRu": "24 часа",
    "year": 2001,
    "endYear": 2014,
    "seasons": 9,
    "episodes": 204,
    "genres": [
      "Боевик",
      "Криминал",
      "Драма",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 8.4,
    "kpRating": 7.9,
    "avgRating": 8.2,
    "description": "Агент Контртеррористического подразделения Джек Бауэр пытается предотвратить теракты в США. Каждый сезон охватывает одни сутки из его жизни, а события развиваются в реальном времени.",
    "poster": "https://image.tmdb.org/t/p/w500/cmIM4XPv4rg05w1MLjnc0mMZhXD.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0285331/",
    "kpUrl": "https://www.kinopoisk.ru/series/77241/",
    "status": "Завершён"
  },
  {
    "id": 43,
    "title": "Homeland",
    "titleRu": "Родина",
    "year": 2011,
    "endYear": 2020,
    "seasons": 8,
    "episodes": 96,
    "genres": [
      "Драма",
      "Детектив",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 8.3,
    "kpRating": 8.1,
    "avgRating": 8.2,
    "description": "Офицер ЦРУ Кэрри Мэтисон подозревает, что спасённый американский морпех перешёл на сторону террористов. Её подозрения перерастают в одержимость.",
    "poster": "https://image.tmdb.org/t/p/w500/hKkntXNF4xgg7HkBy3CIpYnjqoM.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1796960/",
    "kpUrl": "https://www.kinopoisk.ru/series/574625/",
    "status": "Завершён"
  },
  {
    "id": 44,
    "title": "The Walking Dead",
    "titleRu": "Ходячие мертвецы",
    "year": 2010,
    "endYear": 2022,
    "seasons": 11,
    "episodes": 177,
    "genres": [
      "Ужасы",
      "Триллер",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.1,
    "kpRating": 8,
    "avgRating": 8.1,
    "description": "Группа выживших путешествует в поисках безопасного дома после зомби-апокалипсиса. Главной угрозой становятся не только мертвецы, но и другие люди.",
    "poster": "https://image.tmdb.org/t/p/w500/3metsxLVhlJU0mNj5gVfKIih0EF.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1520211/",
    "kpUrl": "https://www.kinopoisk.ru/series/508161/",
    "status": "Завершён"
  },
  {
    "id": 45,
    "title": "Mad Men",
    "titleRu": "Безумцы",
    "year": 2007,
    "endYear": 2015,
    "seasons": 7,
    "episodes": 92,
    "genres": [
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.6,
    "kpRating": 7.9,
    "avgRating": 8.3,
    "description": "Драма о сотрудниках рекламного агентства на Мэдисон-авеню в 1960-е годы. В центре сюжета — блестящий и таинственный креативный директор Дон Дрейпер.",
    "poster": "https://image.tmdb.org/t/p/w500/caYFrMMhiUaRFT8ATiydsBURasN.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0804503/",
    "kpUrl": "https://www.kinopoisk.ru/series/382025/",
    "status": "Завершён"
  },
  {
    "id": 46,
    "title": "Vikings",
    "titleRu": "Викинги",
    "year": 2013,
    "endYear": 2020,
    "seasons": 6,
    "episodes": 89,
    "genres": [
      "Боевик",
      "Приключения",
      "Драма",
      "Исторический"
    ],
    "country": "Ирландия",
    "imdbRating": 8.5,
    "kpRating": 8.2,
    "avgRating": 8.4,
    "description": "Эпическая сага о приключениях и завоеваниях легендарного вождя викингов Рагнара Лодброка и его сыновей. Сериал основан на скандинавских сагах.",
    "poster": "https://image.tmdb.org/t/p/w500/1de3R902B5EEMmohBQsExd5V87Y.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2306299/",
    "kpUrl": "https://www.kinopoisk.ru/series/682255/",
    "status": "Завершён"
  },
  {
    "id": 47,
    "title": "The Witcher",
    "titleRu": "Ведьмак",
    "year": 2019,
    "endYear": null,
    "seasons": 3,
    "episodes": 24,
    "genres": [
      "Фэнтези",
      "Приключения",
      "Драма",
      "Боевик"
    ],
    "country": "США",
    "imdbRating": 8,
    "kpRating": 7.2,
    "avgRating": 7.6,
    "description": "Геральт из Ривии, мутант и убийца чудовищ, изо всех сил старается найти своё место в мире, где люди часто оказываются хуже монстров. Судьба сводит его с могущественной чародейкой и юной принцессой.",
    "poster": "https://image.tmdb.org/t/p/w500/rY2c2LhN07CRKlAbRaDZxN2XjvK.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt5180504/",
    "kpUrl": "https://www.kinopoisk.ru/series/1044004/",
    "status": "Выходит"
  },
  {
    "id": 48,
    "title": "Westworld",
    "titleRu": "Мир Дикого Запада",
    "year": 2016,
    "endYear": 2022,
    "seasons": 4,
    "episodes": 36,
    "genres": [
      "Фантастика",
      "Драма",
      "Детектив"
    ],
    "country": "США",
    "imdbRating": 8.5,
    "kpRating": 7.9,
    "avgRating": 8.2,
    "description": "Футуристический парк развлечений населён андроидами. Посетители могут безнаказанно удовлетворять свои самые низменные желания, пока роботы не начинают обретать сознание.",
    "poster": "https://image.tmdb.org/t/p/w500/j6fldQaouy30RJRfKbp4GRCQfle.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0475784/",
    "kpUrl": "https://www.kinopoisk.ru/series/811077/",
    "status": "Завершён"
  },
  {
    "id": 49,
    "title": "Mr. Robot",
    "titleRu": "Мистер Робот",
    "year": 2015,
    "endYear": 2019,
    "seasons": 4,
    "episodes": 45,
    "genres": [
      "Драма",
      "Криминал",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 8.5,
    "kpRating": 7.8,
    "avgRating": 8.2,
    "description": "Молодой программист Эллиот, страдающий социофобией, днём работает инженером по кибербезопасности, а ночью — хакером. Он втягивается в деятельность подпольной хакерской группы.",
    "poster": "https://image.tmdb.org/t/p/w500/v0O3GfmruiKwBCFUKc1cEM1PVLF.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt4158110/",
    "kpUrl": "https://www.kinopoisk.ru/series/859908/",
    "status": "Завершён"
  },
  {
    "id": 50,
    "title": "Silicon Valley",
    "titleRu": "Кремниевая долина",
    "year": 2014,
    "endYear": 2019,
    "seasons": 6,
    "episodes": 53,
    "genres": [
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.5,
    "kpRating": 8.4,
    "avgRating": 8.5,
    "description": "Группа разработчиков-интровертов пытается запустить свой стартап в Кремниевой долине. Комедия о высоких технологиях, конкуренции и бизнесе.",
    "poster": "https://image.tmdb.org/t/p/w500/hq55ekoWj3zHfBM8RoyxYcw64l3.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2575988/",
    "kpUrl": "https://www.kinopoisk.ru/series/723959/",
    "status": "Завершён"
  },
  {
    "id": 51,
    "title": "Veep",
    "titleRu": "Вице-президент",
    "year": 2012,
    "endYear": 2019,
    "seasons": 7,
    "episodes": 65,
    "genres": [
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.4,
    "kpRating": 7.4,
    "avgRating": 7.9,
    "description": "Селина Майер становится вице-президентом США и обнаруживает, что эта должность совсем не такая, как она ожидала. Сатирический взгляд на американскую политику.",
    "poster": "https://image.tmdb.org/t/p/w500/y00ypo93LgdTuhOmAtb9i3c1XGX.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1759761/",
    "kpUrl": "https://www.kinopoisk.ru/series/589088/",
    "status": "Завершён"
  },
  {
    "id": 52,
    "title": "Curb Your Enthusiasm",
    "titleRu": "Умерь свой энтузиазм",
    "year": 2000,
    "endYear": 2024,
    "seasons": 12,
    "episodes": 120,
    "genres": [
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.8,
    "kpRating": 7.7,
    "avgRating": 8.3,
    "description": "Ларри Дэвид, соавтор сериала «Сайнфелд», играет вымышленную версию самого себя. Он постоянно попадает в неловкие ситуации из-за своего неуживчивого характера.",
    "poster": "https://image.tmdb.org/t/p/w500/l3oqBd9bnkVKIx6QaQe3iGuFmGV.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0264235/",
    "kpUrl": "https://www.kinopoisk.ru/series/252119/",
    "status": "Завершён"
  },
  {
    "id": 53,
    "title": "Seinfeld",
    "titleRu": "Сайнфелд",
    "year": 1989,
    "endYear": 1998,
    "seasons": 9,
    "episodes": 180,
    "genres": [
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.9,
    "kpRating": 7.8,
    "avgRating": 8.4,
    "description": "Культовый комедийный сериал «ни о чём». Стендап-комик Джерри Сайнфелд и его эксцентричные друзья живут в Нью-Йорке и обсуждают мелочи повседневной жизни.",
    "poster": "https://image.tmdb.org/t/p/w500/xLO8d7auctnCgOGJSoyiiaWmDOa.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0098904/",
    "kpUrl": "https://www.kinopoisk.ru/series/194165/",
    "status": "Завершён"
  },
  {
    "id": 54,
    "title": "How I Met Your Mother",
    "titleRu": "Как я встретил вашу маму",
    "year": 2005,
    "endYear": 2014,
    "seasons": 9,
    "episodes": 208,
    "genres": [
      "Комедия",
      "Мелодрама"
    ],
    "country": "США",
    "imdbRating": 8.3,
    "kpRating": 8.6,
    "avgRating": 8.5,
    "description": "Тед Мосби в 2030 году рассказывает своим детям долгую и запутанную историю о том, как он познакомился с их матерью.",
    "poster": "https://image.tmdb.org/t/p/w500/bcd5s6VHINRMEnnt4zXtd3m1GCO.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0460649/",
    "kpUrl": "https://www.kinopoisk.ru/series/258049/",
    "status": "Завершён"
  },
  {
    "id": 55,
    "title": "The Big Bang Theory",
    "titleRu": "Теория большого взрыва",
    "year": 2007,
    "endYear": 2019,
    "seasons": 12,
    "episodes": 279,
    "genres": [
      "Комедия",
      "Мелодрама"
    ],
    "country": "США",
    "imdbRating": 8.2,
    "kpRating": 8.6,
    "avgRating": 8.4,
    "description": "Два блестящих физика-гика сталкиваются с реальным миром, когда по соседству с ними поселяется привлекательная блондинка Пенни.",
    "poster": "https://image.tmdb.org/t/p/w500/wgCVpWDwc93wHlck8jEQT08tps0.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0898266/",
    "kpUrl": "https://www.kinopoisk.ru/series/306084/",
    "status": "Завершён"
  },
  {
    "id": 56,
    "title": "Modern Family",
    "titleRu": "Американская семейка",
    "year": 2009,
    "endYear": 2020,
    "seasons": 11,
    "episodes": 250,
    "genres": [
      "Комедия",
      "Мелодрама"
    ],
    "country": "США",
    "imdbRating": 8.5,
    "kpRating": 8.1,
    "avgRating": 8.3,
    "description": "Псевдодокументальный сериал о трёх разных, но связанных между собой семьях, которые сталкиваются с типичными проблемами современной жизни.",
    "poster": "https://image.tmdb.org/t/p/w500/tbTOeLXT56sywk7OS0qCaHzFNO6.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1442437/",
    "kpUrl": "https://www.kinopoisk.ru/series/477277/",
    "status": "Завершён"
  },
  {
    "id": 57,
    "title": "Brooklyn Nine-Nine",
    "titleRu": "Бруклин 9-9",
    "year": 2013,
    "endYear": 2021,
    "seasons": 8,
    "episodes": 153,
    "genres": [
      "Комедия",
      "Криминал"
    ],
    "country": "США",
    "imdbRating": 8.4,
    "kpRating": 8.2,
    "avgRating": 8.3,
    "description": "История о несерьезном, но талантливом детективе Джейке Перальте и его коллегах из вымышленного полицейского участка Бруклина.",
    "poster": "https://image.tmdb.org/t/p/w500/77mEUuM28cSV8YSn4EcF3koRHHT.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2467372/",
    "kpUrl": "https://www.kinopoisk.ru/series/750051/",
    "status": "Завершён"
  },
  {
    "id": 58,
    "title": "Parks and Recreation",
    "titleRu": "Парки и зоны отдыха",
    "year": 2009,
    "endYear": 2015,
    "seasons": 7,
    "episodes": 125,
    "genres": [
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.6,
    "kpRating": 8.2,
    "avgRating": 8.4,
    "description": "Лесли Ноуп, заместитель директора департамента парков, изо всех сил старается сделать свой родной город лучше, несмотря на бюрократию и безразличие коллег.",
    "poster": "https://image.tmdb.org/t/p/w500/95ilzv0DIxYfu6ahbxkYhm4pk2I.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1266020/",
    "kpUrl": "https://www.kinopoisk.ru/series/428135/",
    "status": "Завершён"
  },
  {
    "id": 59,
    "title": "Arrested Development",
    "titleRu": "Задержка в развитии",
    "year": 2003,
    "endYear": 2019,
    "seasons": 5,
    "episodes": 84,
    "genres": [
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.7,
    "kpRating": 7.7,
    "avgRating": 8.2,
    "description": "Майкл Блут вынужден взять на себя управление семейным бизнесом после того, как его отца сажают в тюрьму за мошенничество. Семья привыкла к роскоши и отказывается менять привычки.",
    "poster": "https://image.tmdb.org/t/p/w500/p4r4RD7RsNcJVoz0H6z3dBoTBtW.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0367279/",
    "kpUrl": "https://www.kinopoisk.ru/series/193072/",
    "status": "Завершён"
  },
  {
    "id": 60,
    "title": "It's Always Sunny in Philadelphia",
    "titleRu": "В Филадельфии всегда солнечно",
    "year": 2005,
    "endYear": null,
    "seasons": 16,
    "episodes": 170,
    "genres": [
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.8,
    "kpRating": 8,
    "avgRating": 8.4,
    "description": "Группа эгоистичных и аморальных друзей управляет ирландским пабом в Филадельфии. Они постоянно втягиваются в абсурдные и скандальные ситуации.",
    "poster": "https://image.tmdb.org/t/p/w500/4UdSBWmizXJAAtlbiYw24i5TNgW.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0472954/",
    "kpUrl": "https://www.kinopoisk.ru/series/257321/",
    "status": "Выходит"
  },
  {
    "id": 61,
    "title": "Archer",
    "titleRu": "Арчер",
    "year": 2009,
    "endYear": 2023,
    "seasons": 14,
    "episodes": 145,
    "genres": [
      "Анимация",
      "Комедия",
      "Боевик"
    ],
    "country": "США",
    "imdbRating": 8.6,
    "kpRating": 8,
    "avgRating": 8.3,
    "description": "Стерлинг Арчер — самовлюблённый и безответственный шпион, работающий в агентстве своей властной матери. Анимационная комедия для взрослых.",
    "poster": "https://image.tmdb.org/t/p/w500/vkbRJxOAEiCaWtjBPaXhihJrDna.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1486217/",
    "kpUrl": "https://www.kinopoisk.ru/series/482860/",
    "status": "Завершён"
  },
  {
    "id": 62,
    "title": "Rick and Morty",
    "titleRu": "Рик и Морти",
    "year": 2013,
    "endYear": null,
    "seasons": 7,
    "episodes": 71,
    "genres": [
      "Анимация",
      "Фантастика",
      "Комедия",
      "Приключения"
    ],
    "country": "США",
    "imdbRating": 9.1,
    "kpRating": 9,
    "avgRating": 9.1,
    "description": "Безумный учёный Рик Санчез и его пугливый внук Морти путешествуют по параллельным мирам и вселенным, попадая в невероятные приключения.",
    "poster": "https://image.tmdb.org/t/p/w500/6D1NA4IMUFI8lBNuCBUlp7eLYDP.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2861424/",
    "kpUrl": "https://www.kinopoisk.ru/series/902086/",
    "status": "Выходит"
  },
  {
    "id": 63,
    "title": "BoJack Horseman",
    "titleRu": "Конь БоДжек",
    "year": 2014,
    "endYear": 2020,
    "seasons": 6,
    "episodes": 77,
    "genres": [
      "Анимация",
      "Драма",
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.8,
    "kpRating": 8.4,
    "avgRating": 8.6,
    "description": "В мире, где люди и антропоморфные животные живут вместе, забытая звезда ситкома 90-х конь БоДжек пытается вернуть былую славу. Глубокая драма о депрессии и одиночестве.",
    "poster": "https://image.tmdb.org/t/p/w500/t4on3Lm3thEIOHVBJdb6T637mbT.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt3398228/",
    "kpUrl": "https://www.kinopoisk.ru/series/840584/",
    "status": "Завершён"
  },
  {
    "id": 64,
    "title": "Avatar: The Last Airbender",
    "titleRu": "Аватар: Легенда об Аанге",
    "year": 2005,
    "endYear": 2008,
    "seasons": 3,
    "episodes": 61,
    "genres": [
      "Анимация",
      "Фэнтези",
      "Боевик",
      "Приключения"
    ],
    "country": "США",
    "imdbRating": 9.3,
    "kpRating": 8.7,
    "avgRating": 9,
    "description": "Мальчик по имени Аанг, обладающий магией всех четырёх стихий, должен остановить войну, развязанную Народом Огня, и восстановить баланс в мире.",
    "poster": "https://image.tmdb.org/t/p/w500/RItCQzeGgdJsqWfIpXwSrWLQiP.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0417299/",
    "kpUrl": "https://www.kinopoisk.ru/series/269926/",
    "status": "Завершён"
  },
  {
    "id": 65,
    "title": "Arcane",
    "titleRu": "Аркейн",
    "year": 2021,
    "endYear": null,
    "seasons": 1,
    "episodes": 9,
    "genres": [
      "Анимация",
      "Фэнтези",
      "Боевик",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 9,
    "kpRating": 8.8,
    "avgRating": 8.9,
    "description": "История разворачивается в утопическом Пилтовере и жестоком Зауне. Сериал рассказывает о происхождении двух культовых чемпионов League of Legends и о силе, которая разведёт их по разные стороны баррикад.",
    "poster": "https://image.tmdb.org/t/p/w500/kVioUjk1SXGWblJNaKsIJcBqUcY.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt11126994/",
    "kpUrl": "https://www.kinopoisk.ru/series/1318784/",
    "status": "Выходит"
  },
  {
    "id": 66,
    "title": "The Simpsons",
    "titleRu": "Симпсоны",
    "year": 1989,
    "endYear": null,
    "seasons": 35,
    "episodes": 768,
    "genres": [
      "Анимация",
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.7,
    "kpRating": 8.4,
    "avgRating": 8.6,
    "description": "Самый длинный мультсериал в истории американского телевидения. Сатирический взгляд на жизнь американской семьи среднего класса в вымышленном городе Спрингфилд.",
    "poster": "https://image.tmdb.org/t/p/w500/171yRAHGCziNjtO53sEil1PH64v.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0096697/",
    "kpUrl": "https://www.kinopoisk.ru/series/77385/",
    "status": "Выходит"
  },
  {
    "id": 67,
    "title": "South Park",
    "titleRu": "Южный Парк",
    "year": 1997,
    "endYear": null,
    "seasons": 26,
    "episodes": 328,
    "genres": [
      "Анимация",
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.7,
    "kpRating": 8.1,
    "avgRating": 8.4,
    "description": "Мультсериал, известный своим черным юмором и сатирой на американскую культуру. Четверо школьников живут в городке Саут-Парк и постоянно попадают в абсурдные ситуации.",
    "poster": "https://image.tmdb.org/t/p/w500/69lJGPmFoUplHWoVnCbCcXKRqOl.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0121955/",
    "kpUrl": "https://www.kinopoisk.ru/series/77519/",
    "status": "Выходит"
  },
  {
    "id": 68,
    "title": "Futurama",
    "titleRu": "Футурама",
    "year": 1999,
    "endYear": null,
    "seasons": 11,
    "episodes": 150,
    "genres": [
      "Анимация",
      "Фантастика",
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.5,
    "kpRating": 8.1,
    "avgRating": 8.3,
    "description": "Разносчик пиццы случайно замораживает себя в криогенной камере в 1999 году и просыпается в Новом Нью-Йорке тысячу лет спустя.",
    "poster": "https://image.tmdb.org/t/p/w500/sbjCH9Ed1G97Z0ESawKbOamJi5y.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0149460/",
    "kpUrl": "https://www.kinopoisk.ru/series/77335/",
    "status": "Выходит"
  },
  {
    "id": 69,
    "title": "Family Guy",
    "titleRu": "Гриффины",
    "year": 1999,
    "endYear": null,
    "seasons": 22,
    "episodes": 424,
    "genres": [
      "Анимация",
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.1,
    "kpRating": 7.7,
    "avgRating": 7.9,
    "description": "Комедийный мультсериал о жизни неблагополучной семьи Гриффинов, состоящей из глуповатого Питера, его жены Лоис, троих детей и говорящей собаки Брайана.",
    "poster": "https://image.tmdb.org/t/p/w500/9zdZeAxt7Xxu5omPufFu1TMl8BP.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0182576/",
    "kpUrl": "https://www.kinopoisk.ru/series/77508/",
    "status": "Выходит"
  },
  {
    "id": 70,
    "title": "Attack on Titan",
    "titleRu": "Атака титанов",
    "year": 2013,
    "endYear": 2023,
    "seasons": 4,
    "episodes": 89,
    "genres": [
      "Анимация",
      "Фэнтези",
      "Боевик",
      "Драма"
    ],
    "country": "Япония",
    "imdbRating": 9,
    "kpRating": 8.7,
    "avgRating": 8.9,
    "description": "Человечество живёт за огромными стенами, скрываясь от гигантских титанов-людоедов. Молодой Эрен Йегер клянётся уничтожить их всех после того, как титаны разрушают его дом.",
    "poster": "https://image.tmdb.org/t/p/w500/9whSxgqSW7dPIIMJyM4WG3BYVo7.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2560140/",
    "kpUrl": "https://www.kinopoisk.ru/series/748577/",
    "status": "Завершён"
  },
  {
    "id": 71,
    "title": "Death Note",
    "titleRu": "Тетрадь смерти",
    "year": 2006,
    "endYear": 2007,
    "seasons": 1,
    "episodes": 37,
    "genres": [
      "Анимация",
      "Детектив",
      "Триллер",
      "Драма"
    ],
    "country": "Япония",
    "imdbRating": 8.9,
    "kpRating": 8.6,
    "avgRating": 8.8,
    "description": "Одарённый школьник Лайт Ягами находит Тетрадь смерти — мистический предмет, позволяющий убить любого человека, чьё имя в неё вписано. Он решает очистить мир от преступников.",
    "poster": "https://image.tmdb.org/t/p/w500/gctfvLTh6yn0F6AiO20Me5DmwO5.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0877057/",
    "kpUrl": "https://www.kinopoisk.ru/series/406148/",
    "status": "Завершён"
  },
  {
    "id": 72,
    "title": "Naruto",
    "titleRu": "Наруто",
    "year": 2002,
    "endYear": 2007,
    "seasons": 5,
    "episodes": 220,
    "genres": [
      "Анимация",
      "Боевик",
      "Приключения"
    ],
    "country": "Япония",
    "imdbRating": 8.4,
    "kpRating": 8,
    "avgRating": 8.2,
    "description": "Юный ниндзя Наруто Узумаки, в теле которого запечатан Девятихвостый Лис, мечтает стать Хокаге — лидером своей деревни.",
    "poster": "https://image.tmdb.org/t/p/w500/ply5yM9ylDMy8t13pkqKmJlLsJP.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0409591/",
    "kpUrl": "https://www.kinopoisk.ru/series/194305/",
    "status": "Завершён"
  },
  {
    "id": 73,
    "title": "One Piece",
    "titleRu": "Ван-Пис",
    "year": 1999,
    "endYear": null,
    "seasons": 20,
    "episodes": 1100,
    "genres": [
      "Анимация",
      "Боевик",
      "Приключения",
      "Комедия"
    ],
    "country": "Япония",
    "imdbRating": 8.9,
    "kpRating": 8.6,
    "avgRating": 8.8,
    "description": "Манки Д. Луффи и его команда пиратов Соломенной Шляпы исследуют Гранд Лайн в поисках легендарного сокровища, чтобы Луффи смог стать Королём Пиратов.",
    "poster": "https://image.tmdb.org/t/p/w500/osRT8GsND3PfhvevsS5DK9px0LI.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0388629/",
    "kpUrl": "https://www.kinopoisk.ru/series/236109/",
    "status": "Выходит"
  },
  {
    "id": 74,
    "title": "Demon Slayer",
    "titleRu": "Истребитель демонов",
    "year": 2019,
    "endYear": null,
    "seasons": 4,
    "episodes": 55,
    "genres": [
      "Анимация",
      "Боевик",
      "Фэнтези"
    ],
    "country": "Япония",
    "imdbRating": 8.6,
    "kpRating": 8.2,
    "avgRating": 8.4,
    "description": "Мальчик по имени Тандзиро становится истребителем демонов после того, как его семья была убита, а сестра превращена в демона.",
    "poster": "https://image.tmdb.org/t/p/w500/zg3GrU3jAoTGxmlGGhkfNYMOHlb.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt9335498/",
    "kpUrl": "https://www.kinopoisk.ru/series/1242337/",
    "status": "Выходит"
  },
  {
    "id": 75,
    "title": "Fullmetal Alchemist: Brotherhood",
    "titleRu": "Стальной алхимик: Братство",
    "year": 2009,
    "endYear": 2010,
    "seasons": 1,
    "episodes": 64,
    "genres": [
      "Анимация",
      "Боевик",
      "Приключения",
      "Драма"
    ],
    "country": "Япония",
    "imdbRating": 9.1,
    "kpRating": 8.7,
    "avgRating": 8.9,
    "description": "Братья Эдвард и Альфонс Элрики ищут философский камень, чтобы вернуть свои тела после неудачной попытки воскресить мать с помощью алхимии.",
    "poster": "https://image.tmdb.org/t/p/w500/n2M0BslYmciTcxHc0SpwSljujUG.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1453612/",
    "kpUrl": "https://www.kinopoisk.ru/series/470001/",
    "status": "Завершён"
  },
  {
    "id": 76,
    "title": "Method",
    "titleRu": "Метод",
    "year": 2015,
    "endYear": null,
    "seasons": 2,
    "episodes": 32,
    "genres": [
      "Триллер",
      "Криминал",
      "Детектив"
    ],
    "country": "Россия",
    "imdbRating": 7.3,
    "kpRating": 8.2,
    "avgRating": 7.8,
    "description": "Следователь Родион Меглин раскрывает самые сложные убийства. Он привык работать в одиночку, пока к нему не прикрепляют стажёрку Есеню.",
    "poster": "https://image.tmdb.org/t/p/w500/bChmceUFowRGkwghHw8EePyYSch.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt4466548/",
    "kpUrl": "https://www.kinopoisk.ru/series/842366/",
    "status": "Выходит"
  },
  {
    "id": 77,
    "title": "To the Lake",
    "titleRu": "Эпидемия",
    "year": 2019,
    "endYear": 2022,
    "seasons": 2,
    "episodes": 16,
    "genres": [
      "Триллер",
      "Драма",
      "Фантастика"
    ],
    "country": "Россия",
    "imdbRating": 7.2,
    "kpRating": 7.8,
    "avgRating": 7.5,
    "description": "Неизвестный вирус поражает Москву, превращая её в город мёртвых. Главный герой спасает свою семью и пытается добраться до убежища в Карелии.",
    "poster": "https://image.tmdb.org/t/p/w500/sGH8stoSIIGgvitSOQSuCnse21O.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt9151230/",
    "kpUrl": "https://www.kinopoisk.ru/series/1218520/",
    "status": "Завершён"
  },
  {
    "id": 78,
    "title": "Silver Spoon",
    "titleRu": "Мажор",
    "year": 2014,
    "endYear": 2022,
    "seasons": 4,
    "episodes": 48,
    "genres": [
      "Драма",
      "Криминал",
      "Комедия"
    ],
    "country": "Россия",
    "imdbRating": 7.7,
    "kpRating": 8.3,
    "avgRating": 8,
    "description": "Избалованный сын олигарха после очередного проступка отправляется работать в обычное отделение полиции. Там он меняет взгляды на жизнь.",
    "poster": "https://image.tmdb.org/t/p/w500/kDEpaBqnD40tI7XpRDUFWn4JWcA.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt4568600/",
    "kpUrl": "https://www.kinopoisk.ru/series/841005/",
    "status": "Завершён"
  },
  {
    "id": 79,
    "title": "Kitchen",
    "titleRu": "Кухня",
    "year": 2012,
    "endYear": 2016,
    "seasons": 6,
    "episodes": 120,
    "genres": [
      "Комедия"
    ],
    "country": "Россия",
    "imdbRating": 8.2,
    "kpRating": 8.3,
    "avgRating": 8.3,
    "description": "Молодой повар Максим устраивается в элитный ресторан французской кухни в Москве. На кухне царит хаос, которым управляет шеф-повар Виктор Баринов.",
    "poster": "https://image.tmdb.org/t/p/w500/juqlBUbTxc4T90lMSYxvEYTQsL.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2991040/",
    "kpUrl": "https://www.kinopoisk.ru/series/737604/",
    "status": "Завершён"
  },
  {
    "id": 80,
    "title": "Interns",
    "titleRu": "Интерны",
    "year": 2010,
    "endYear": 2016,
    "seasons": 14,
    "episodes": 280,
    "genres": [
      "Комедия"
    ],
    "country": "Россия",
    "imdbRating": 7.6,
    "kpRating": 7.5,
    "avgRating": 7.6,
    "description": "Четверо молодых врачей-интернов постоянно попадают в глупые ситуации под руководством циничного заведующего отделением Быкова.",
    "poster": "https://image.tmdb.org/t/p/w500/nGRNrIyBo6J0WiuCtlammxtSUoC.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1643446/",
    "kpUrl": "https://www.kinopoisk.ru/series/505866/",
    "status": "Завершён"
  },
  {
    "id": 81,
    "title": "Fizruk",
    "titleRu": "Физрук",
    "year": 2014,
    "endYear": 2017,
    "seasons": 4,
    "episodes": 77,
    "genres": [
      "Комедия"
    ],
    "country": "Россия",
    "imdbRating": 7.2,
    "kpRating": 7.8,
    "avgRating": 7.5,
    "description": "Криминальный авторитет из 90-х устраивается работать физруком в школу, чтобы подобраться к ребенку своего бывшего босса и вернуть работу.",
    "poster": "https://image.tmdb.org/t/p/w500/1Q8kgITlWOvJmGA3NgPqpcmhKfB.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt3595786/",
    "kpUrl": "https://www.kinopoisk.ru/series/818967/",
    "status": "Завершён"
  },
  {
    "id": 82,
    "title": "Chernobyl: Zone of Exclusion",
    "titleRu": "Чернобыль: Зона отчуждения",
    "year": 2014,
    "endYear": 2019,
    "seasons": 2,
    "episodes": 16,
    "genres": [
      "Триллер",
      "Фантастика",
      "Мистика"
    ],
    "country": "Россия",
    "imdbRating": 7.2,
    "kpRating": 7.9,
    "avgRating": 7.6,
    "description": "Пятеро друзей отправляются на старой Волге в Припять, чтобы догнать вора. Там они сталкиваются с мистической Зоной отчуждения.",
    "poster": "https://image.tmdb.org/t/p/w500/cGM5mvXOzwGdOr7uPJ1NNedapYE.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt4228308/",
    "kpUrl": "https://www.kinopoisk.ru/series/776269/",
    "status": "Завершён"
  },
  {
    "id": 83,
    "title": "Magnificent Century",
    "titleRu": "Великолепный век",
    "year": 2011,
    "endYear": 2014,
    "seasons": 4,
    "episodes": 139,
    "genres": [
      "Драма",
      "Исторический",
      "Мелодрама"
    ],
    "country": "Турция",
    "imdbRating": 6.9,
    "kpRating": 8.2,
    "avgRating": 7.6,
    "description": "История правления султана Сулеймана Великолепного и его страстной любви к славянской рабыне Хюррем, ставшей самой влиятельной женщиной Османской империи.",
    "poster": "https://image.tmdb.org/t/p/w500/vYKtZlzS0NEFoIv2myhTZdrY4xQ.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1848220/",
    "kpUrl": "https://www.kinopoisk.ru/series/581977/",
    "status": "Завершён"
  },
  {
    "id": 84,
    "title": "You Knock on My Door",
    "titleRu": "Постучись в мою дверь",
    "year": 2020,
    "endYear": 2021,
    "seasons": 2,
    "episodes": 52,
    "genres": [
      "Мелодрама",
      "Комедия"
    ],
    "country": "Турция",
    "imdbRating": 7.1,
    "kpRating": 8.1,
    "avgRating": 7.6,
    "description": "Студентка Эда и богатый бизнесмен Серкан заключают фиктивную помолвку. Вскоре их притворство перерастает в настоящие чувства.",
    "poster": "https://image.tmdb.org/t/p/w500/2aqsQfjBEOdt4oZ8xk6XR2lKkDm.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt12439466/",
    "kpUrl": "https://www.kinopoisk.ru/series/1379768/",
    "status": "Завершён"
  },
  {
    "id": 85,
    "title": "Endless Love",
    "titleRu": "Чёрная любовь",
    "year": 2015,
    "endYear": 2017,
    "seasons": 2,
    "episodes": 74,
    "genres": [
      "Драма",
      "Мелодрама"
    ],
    "country": "Турция",
    "imdbRating": 7.4,
    "kpRating": 8.3,
    "avgRating": 7.9,
    "description": "Кемаль и Нихан принадлежат к разным мирам, но влюбляются друг в друга. Их любви предстоит пройти через множество испытаний и трагедий.",
    "poster": "https://image.tmdb.org/t/p/w500/sxGRz9F4YgigJor3Y45rTvOxJon.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt5251458/",
    "kpUrl": "https://www.kinopoisk.ru/series/967266/",
    "status": "Завершён"
  },
  {
    "id": 86,
    "title": "Kingdom",
    "titleRu": "Королевство",
    "year": 2019,
    "endYear": null,
    "seasons": 2,
    "episodes": 12,
    "genres": [
      "Боевик",
      "Триллер",
      "Ужасы"
    ],
    "country": "Южная Корея",
    "imdbRating": 8.3,
    "kpRating": 7.7,
    "avgRating": 8,
    "description": "В государстве Чосон распространяется загадочная болезнь, превращающая людей в зомби. Наследный принц отправляется в путешествие, чтобы спасти страну.",
    "poster": "https://image.tmdb.org/t/p/w500/eXRWYkffOq0be8hNlQTNeB0yLPX.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2278388/",
    "kpUrl": "https://www.kinopoisk.ru/series/1118128/",
    "status": "Выходит"
  },
  {
    "id": 87,
    "title": "My Love from the Star",
    "titleRu": "Человек со звезды",
    "year": 2013,
    "endYear": 2014,
    "seasons": 1,
    "episodes": 21,
    "genres": [
      "Комедия",
      "Мелодрама",
      "Фантастика"
    ],
    "country": "Южная Корея",
    "imdbRating": 8.2,
    "kpRating": 8.3,
    "avgRating": 8.3,
    "description": "Инопланетянин, застрявший на Земле 400 лет назад, влюбляется в известную актрису незадолго до своего возвращения на родную планету.",
    "poster": "https://image.tmdb.org/t/p/w500/x2PJLhpjlJpAflUpzcBnzDaNOmE.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt3398220/",
    "kpUrl": "https://www.kinopoisk.ru/series/818817/",
    "status": "Завершён"
  },
  {
    "id": 88,
    "title": "Crash Landing on You",
    "titleRu": "Аварийная посадка любви",
    "year": 2019,
    "endYear": 2020,
    "seasons": 1,
    "episodes": 16,
    "genres": [
      "Комедия",
      "Мелодрама"
    ],
    "country": "Южная Корея",
    "imdbRating": 8.7,
    "kpRating": 8.5,
    "avgRating": 8.6,
    "description": "Богатая наследница из Южной Кореи во время полета на параплане случайно приземляется в Северной Корее, где встречает офицера местной армии.",
    "poster": "https://image.tmdb.org/t/p/w500/mvy18bPg93JNLwTQHHP2ZjPYP0A.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt10850426/",
    "kpUrl": "https://www.kinopoisk.ru/series/1301980/",
    "status": "Завершён"
  },
  {
    "id": 89,
    "title": "All of Us Are Dead",
    "titleRu": "Мы все мертвы",
    "year": 2022,
    "endYear": null,
    "seasons": 1,
    "episodes": 12,
    "genres": [
      "Ужасы",
      "Боевик",
      "Драма"
    ],
    "country": "Южная Корея",
    "imdbRating": 7.5,
    "kpRating": 6.9,
    "avgRating": 7.2,
    "description": "Школа становится эпицентром вспышки зомби-вируса. Старшеклассники оказываются в ловушке и должны сражаться за свою жизнь.",
    "poster": "https://image.tmdb.org/t/p/w500/7PIItwy2Eby1z7jruewAeMH9NaL.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt14169960/",
    "kpUrl": "https://www.kinopoisk.ru/series/1367807/",
    "status": "Выходит"
  },
  {
    "id": 90,
    "title": "Borgen",
    "titleRu": "Правительство",
    "year": 2010,
    "endYear": 2022,
    "seasons": 4,
    "episodes": 38,
    "genres": [
      "Драма"
    ],
    "country": "Дания",
    "imdbRating": 8.5,
    "kpRating": 8,
    "avgRating": 8.3,
    "description": "Политическая драма о Биргитте Нюборг, первой женщине, ставшей премьер-министром Дании. Сериал исследует влияние власти на человека.",
    "poster": "https://image.tmdb.org/t/p/w500/3wB4R3Ac3lKSQWKpoU0zeRY8XqL.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1526730/",
    "kpUrl": "https://www.kinopoisk.ru/series/584288/",
    "status": "Завершён"
  },
  {
    "id": 91,
    "title": "The Bridge",
    "titleRu": "Мост",
    "year": 2011,
    "endYear": 2018,
    "seasons": 4,
    "episodes": 38,
    "genres": [
      "Триллер",
      "Детектив",
      "Криминал"
    ],
    "country": "Швеция",
    "imdbRating": 8.6,
    "kpRating": 8.3,
    "avgRating": 8.5,
    "description": "На мосту между Данией и Швецией находят труп. За расследование берутся детективы из обеих стран, которым приходится работать вместе.",
    "poster": "https://image.tmdb.org/t/p/w500/jELMtwCSPLO6INY2VzkkBK73cLT.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1733785/",
    "kpUrl": "https://www.kinopoisk.ru/series/630560/",
    "status": "Завершён"
  },
  {
    "id": 92,
    "title": "Elite",
    "titleRu": "Элита",
    "year": 2018,
    "endYear": null,
    "seasons": 8,
    "episodes": 64,
    "genres": [
      "Триллер",
      "Драма",
      "Криминал"
    ],
    "country": "Испания",
    "imdbRating": 7.3,
    "kpRating": 7.7,
    "avgRating": 7.5,
    "description": "Трое подростков из простых семей попадают в самую престижную школу Испании. Их появление приводит к конфликту с богатыми учениками и в конечном итоге к убийству.",
    "poster": "https://image.tmdb.org/t/p/w500/6w6KepHCC8HKq4v9CqDAM706I63.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt7134908/",
    "kpUrl": "https://www.kinopoisk.ru/series/1100331/",
    "status": "Выходит"
  },
  {
    "id": 93,
    "title": "Gomorrah",
    "titleRu": "Гоморра",
    "year": 2014,
    "endYear": 2021,
    "seasons": 5,
    "episodes": 58,
    "genres": [
      "Криминал",
      "Драма",
      "Триллер"
    ],
    "country": "Италия",
    "imdbRating": 8.7,
    "kpRating": 8,
    "avgRating": 8.4,
    "description": "Жестокий реалистичный взгляд на жизнь неаполитанской мафии — Каморры. История борьбы за власть внутри одного из самых могущественных кланов.",
    "poster": "https://image.tmdb.org/t/p/w500/zJvPctn5UGxUwRP3vZDJWJw14RQ.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2049116/",
    "kpUrl": "https://www.kinopoisk.ru/series/818816/",
    "status": "Завершён"
  },
  {
    "id": 94,
    "title": "Sacred Games",
    "titleRu": "Сакральные игры",
    "year": 2018,
    "endYear": 2019,
    "seasons": 2,
    "episodes": 16,
    "genres": [
      "Боевик",
      "Криминал",
      "Драма",
      "Триллер"
    ],
    "country": "Индия",
    "imdbRating": 8.5,
    "kpRating": 7.3,
    "avgRating": 7.9,
    "description": "Честный полицейский получает звонок от беглого криминального авторитета, который предупреждает его об угрозе для Мумбаи. Начинается гонка со временем.",
    "poster": "https://image.tmdb.org/t/p/w500/v68l72g8ycIt4t2sAfoUEoyvjJr.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt6077448/",
    "kpUrl": "https://www.kinopoisk.ru/series/1118182/",
    "status": "Завершён"
  },
  {
    "id": 95,
    "title": "3%",
    "titleRu": "3 процента",
    "year": 2016,
    "endYear": 2020,
    "seasons": 4,
    "episodes": 33,
    "genres": [
      "Фантастика",
      "Драма",
      "Триллер"
    ],
    "country": "Бразилия",
    "imdbRating": 7.3,
    "kpRating": 6.9,
    "avgRating": 7.1,
    "description": "В будущем мир разделён на разрушенную Континент и процветающий Офшор. Каждый год 20-летние молодые люди проходят жестокий отбор, и только 3% из них получают шанс на лучшую жизнь.",
    "poster": "https://image.tmdb.org/t/p/w500/qexbQteX7G3065zAksoPOdz165C.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt5381714/",
    "kpUrl": "https://www.kinopoisk.ru/series/1008605/",
    "status": "Завершён"
  },
  {
    "id": 96,
    "title": "Fauda",
    "titleRu": "Фауда",
    "year": 2015,
    "endYear": null,
    "seasons": 4,
    "episodes": 48,
    "genres": [
      "Боевик",
      "Драма",
      "Триллер"
    ],
    "country": "Израиль",
    "imdbRating": 8.3,
    "kpRating": 7.9,
    "avgRating": 8.1,
    "description": "Командир подразделения Мистаарвим возвращается на службу, чтобы поймать опасного палестинского боевика. Сериал показывает конфликт с обеих сторон.",
    "poster": "https://image.tmdb.org/t/p/w500/taxQfYM8zmy9Gc6qNYUnjr8xwKs.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt4565380/",
    "kpUrl": "https://www.kinopoisk.ru/series/902781/",
    "status": "Выходит"
  },
  {
    "id": 97,
    "title": "True Blood",
    "titleRu": "Настоящая кровь",
    "year": 2008,
    "endYear": 2014,
    "seasons": 7,
    "episodes": 80,
    "genres": [
      "Драма",
      "Фэнтези",
      "Триллер",
      "Детектив"
    ],
    "country": "США",
    "imdbRating": 7.9,
    "kpRating": 7.7,
    "avgRating": 7.8,
    "description": "Изобретение синтетической крови позволило вампирам перестать скрываться и начать открыто жить среди людей. Но интеграция проходит не гладко.",
    "poster": "https://image.tmdb.org/t/p/w500/omEyeccHNi9nQnILoBVlvJiBnXz.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0844441/",
    "kpUrl": "https://www.kinopoisk.ru/series/422882/",
    "status": "Завершён"
  },
  {
    "id": 98,
    "title": "Euphoria",
    "titleRu": "Эйфория",
    "year": 2019,
    "endYear": null,
    "seasons": 2,
    "episodes": 16,
    "genres": [
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.3,
    "kpRating": 7.6,
    "avgRating": 8,
    "description": "Группа старшеклассников исследует мир наркотиков, секса, идентичности и социальных сетей. Визуально яркая и эмоционально тяжелая драма.",
    "poster": "https://image.tmdb.org/t/p/w500/yJz0VPfztciUt8cYulEOnk7wQhs.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt8772296/",
    "kpUrl": "https://www.kinopoisk.ru/series/1173926/",
    "status": "Выходит"
  },
  {
    "id": 99,
    "title": "The White Lotus",
    "titleRu": "Белый лотос",
    "year": 2021,
    "endYear": null,
    "seasons": 2,
    "episodes": 13,
    "genres": [
      "Комедия",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8,
    "kpRating": 7.5,
    "avgRating": 7.8,
    "description": "Сатирическая комедия, рассказывающая о жизни персонала и эксцентричных гостей элитного курорта. С каждым днем напряжение нарастает.",
    "poster": "https://image.tmdb.org/t/p/w500/m50tjkb2PuvVmGHifRpVXCMswxn.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt13406094/",
    "kpUrl": "https://www.kinopoisk.ru/series/1435848/",
    "status": "Выходит"
  },
  {
    "id": 100,
    "title": "The Handmaid's Tale",
    "titleRu": "Рассказ служанки",
    "year": 2017,
    "endYear": null,
    "seasons": 5,
    "episodes": 56,
    "genres": [
      "Драма",
      "Фантастика",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 8.4,
    "kpRating": 7.9,
    "avgRating": 8.2,
    "description": "В тоталитарном государстве Гилеад, где фертильные женщины стали собственностью государства и используются для рождения детей офицерам. Главная героиня пытается выжить и найти свою дочь.",
    "poster": "https://image.tmdb.org/t/p/w500/cRnBbHau8YKuWUeRD2gpdzdRZ2X.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1048578/",
    "kpUrl": "https://www.kinopoisk.ru/series/968132/",
    "status": "Выходит"
  },
  {
    "id": 101,
    "title": "The Queen's Gambit",
    "titleRu": "Ход королевы",
    "year": 2020,
    "endYear": 2020,
    "seasons": 1,
    "episodes": 7,
    "genres": [
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.5,
    "kpRating": 8.3,
    "avgRating": 8.4,
    "description": "История сироты Бет Хармон, которая открывает в себе невероятный талант к шахматам. Она стремится стать величайшим игроком в мире, борясь с зависимостью.",
    "poster": "https://image.tmdb.org/t/p/w500/s2s3E4yNyErQZ081jDEONfLFYxb.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt10048342/",
    "kpUrl": "https://www.kinopoisk.ru/series/1253457/",
    "status": "Завершён"
  },
  {
    "id": 102,
    "title": "Narcos: Mexico",
    "titleRu": "Нарко: Мексика",
    "year": 2018,
    "endYear": 2021,
    "seasons": 3,
    "episodes": 30,
    "genres": [
      "Криминал",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.3,
    "kpRating": 7.9,
    "avgRating": 8.1,
    "description": "Спин-офф сериала Нарко, рассказывающий о зарождении мексиканской войны с наркотиками в 1980-х годах и становлении картеля Гвадалахары.",
    "poster": "https://image.tmdb.org/t/p/w500/jJub1g4bZUJ5y35sCOUBFHrtdkd.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt8762206/",
    "kpUrl": "https://www.kinopoisk.ru/series/1126130/",
    "status": "Завершён"
  },
  {
    "id": 103,
    "title": "Shameless",
    "titleRu": "Бесстыжие",
    "year": 2011,
    "endYear": 2021,
    "seasons": 11,
    "episodes": 134,
    "genres": [
      "Комедия",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.5,
    "kpRating": 8.7,
    "avgRating": 8.6,
    "description": "Многодетная семья Галлагеров живет на окраине Чикаго. Отец-алкоголик пропивает все деньги, а шестеро детей учатся выживать самостоятельно.",
    "poster": "https://image.tmdb.org/t/p/w500/ahhEWtnEnp8TgHAVzD19JGpbIbu.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1586680/",
    "kpUrl": "https://www.kinopoisk.ru/series/571335/",
    "status": "Завершён"
  },
  {
    "id": 104,
    "title": "Suits",
    "titleRu": "Форс-мажоры",
    "year": 2011,
    "endYear": 2019,
    "seasons": 9,
    "episodes": 134,
    "genres": [
      "Драма",
      "Комедия"
    ],
    "country": "США",
    "imdbRating": 8.4,
    "kpRating": 8.6,
    "avgRating": 8.5,
    "description": "Успешный корпоративный юрист Харви Спектер нанимает гениального самоучку Майка Росса, хотя у того нет юридического образования.",
    "poster": "https://image.tmdb.org/t/p/w500/xMh0HsI037m9dgDz1vUlNN66dgx.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1632701/",
    "kpUrl": "https://www.kinopoisk.ru/series/557806/",
    "status": "Завершён"
  },
  {
    "id": 105,
    "title": "Supernatural",
    "titleRu": "Сверхъестественное",
    "year": 2005,
    "endYear": 2020,
    "seasons": 15,
    "episodes": 327,
    "genres": [
      "Драма",
      "Фэнтези",
      "Ужасы",
      "Детектив"
    ],
    "country": "США",
    "imdbRating": 8.4,
    "kpRating": 8.2,
    "avgRating": 8.3,
    "description": "Братья Сэм и Дин Винчестеры путешествуют по Америке на черной Шевроле Импале, расследуя паранормальные явления и сражаясь с демонами.",
    "poster": "https://image.tmdb.org/t/p/w500/hvO99pEfSBxF55clgs8r4mpRzr.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0460681/",
    "kpUrl": "https://www.kinopoisk.ru/series/178707/",
    "status": "Завершён"
  },
  {
    "id": 106,
    "title": "The Vampire Diaries",
    "titleRu": "Дневники вампира",
    "year": 2009,
    "endYear": 2017,
    "seasons": 8,
    "episodes": 171,
    "genres": [
      "Драма",
      "Фэнтези",
      "Ужасы",
      "Мелодрама"
    ],
    "country": "США",
    "imdbRating": 7.7,
    "kpRating": 8,
    "avgRating": 7.9,
    "description": "Старшеклассница Елена Гилберт влюбляется в таинственного Стефана, не подозревая, что он вампир. Вскоре в город возвращается его опасный брат Деймон.",
    "poster": "https://image.tmdb.org/t/p/w500/y8hcR1R8QmGs8uLHQhIFHgCFWDd.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1405406/",
    "kpUrl": "https://www.kinopoisk.ru/series/455153/",
    "status": "Завершён"
  },
  {
    "id": 107,
    "title": "Teen Wolf",
    "titleRu": "Волчонок",
    "year": 2011,
    "endYear": 2017,
    "seasons": 6,
    "episodes": 100,
    "genres": [
      "Боевик",
      "Драма",
      "Фэнтези",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 7.7,
    "kpRating": 7.9,
    "avgRating": 7.8,
    "description": "Жизнь обычного школьника Скотта МакКолла меняется навсегда после того, как в лесу его кусает оборотень. Теперь ему предстоит научиться контролировать новые способности.",
    "poster": "https://image.tmdb.org/t/p/w500/bq0TmDgpYWrTuJVo8JpeMU3LLb8.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt1567432/",
    "kpUrl": "https://www.kinopoisk.ru/series/527814/",
    "status": "Завершён"
  },
  {
    "id": 108,
    "title": "Gossip Girl",
    "titleRu": "Сплетница",
    "year": 2007,
    "endYear": 2012,
    "seasons": 6,
    "episodes": 121,
    "genres": [
      "Драма",
      "Мелодрама"
    ],
    "country": "США",
    "imdbRating": 7.5,
    "kpRating": 8.1,
    "avgRating": 7.8,
    "description": "Жизнь золотой молодежи Манхэттена находится под пристальным вниманием таинственной Сплетницы, которая публикует все их секреты в своем блоге.",
    "poster": "https://image.tmdb.org/t/p/w500/lwpjIGOaGGEScuEVdP5Hp4sNrfP.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt0397442/",
    "kpUrl": "https://www.kinopoisk.ru/series/396030/",
    "status": "Завершён"
  },
  {
    "id": 109,
    "title": "The Flash",
    "titleRu": "Флэш",
    "year": 2014,
    "endYear": 2023,
    "seasons": 9,
    "episodes": 184,
    "genres": [
      "Фантастика",
      "Боевик",
      "Приключения"
    ],
    "country": "США",
    "imdbRating": 7.5,
    "kpRating": 7.5,
    "avgRating": 7.5,
    "description": "Судмедэксперт Барри Аллен обретает способность передвигаться на сверхчеловеческой скорости после удара молнии и становится защитником Централ-сити.",
    "poster": "https://image.tmdb.org/t/p/w500/q14oRmj0ITMBzqHUdiGwXUIvg7t.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt3107288/",
    "kpUrl": "https://www.kinopoisk.ru/series/817506/",
    "status": "Завершён"
  },
  {
    "id": 110,
    "title": "Arrow",
    "titleRu": "Стрела",
    "year": 2012,
    "endYear": 2020,
    "seasons": 8,
    "episodes": 170,
    "genres": [
      "Боевик",
      "Криминал",
      "Драма",
      "Детектив"
    ],
    "country": "США",
    "imdbRating": 7.5,
    "kpRating": 7.5,
    "avgRating": 7.5,
    "description": "Миллиардер Оливер Куин, которого считали погибшим, возвращается домой. По ночам он надевает костюм и становится мстителем, вооруженным луком и стрелами.",
    "poster": "https://image.tmdb.org/t/p/w500/8xevzZgfa6ed0vVrZ8kwf71py4w.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2193021/",
    "kpUrl": "https://www.kinopoisk.ru/series/664147/",
    "status": "Завершён"
  },
  {
    "id": 111,
    "title": "Daredevil",
    "titleRu": "Сорвиголова",
    "year": 2015,
    "endYear": 2018,
    "seasons": 3,
    "episodes": 39,
    "genres": [
      "Боевик",
      "Криминал",
      "Драма",
      "Фантастика"
    ],
    "country": "США",
    "imdbRating": 8.6,
    "kpRating": 8.1,
    "avgRating": 8.4,
    "description": "Слепой адвокат Мэтт Мердок борется с преступностью в Адской Кухне Нью-Йорка: днем в зале суда, а ночью — как мститель в маске.",
    "poster": "https://image.tmdb.org/t/p/w500/c47xj2YlMKPEMbLXlLriZaRnlXu.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt3322312/",
    "kpUrl": "https://www.kinopoisk.ru/series/820703/",
    "status": "Завершён"
  },
  {
    "id": 112,
    "title": "The Punisher",
    "titleRu": "Каратель",
    "year": 2017,
    "endYear": 2019,
    "seasons": 2,
    "episodes": 26,
    "genres": [
      "Боевик",
      "Криминал",
      "Драма",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 8.5,
    "kpRating": 7.9,
    "avgRating": 8.2,
    "description": "Ветеран морской пехоты Фрэнк Касл, чья семья была жестоко убита, становится Карателем. Он использует смертоносные методы для борьбы с преступностью.",
    "poster": "https://image.tmdb.org/t/p/w500/wUlX8npglxkoj8OX5eK8HpLoWSj.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt5675620/",
    "kpUrl": "https://www.kinopoisk.ru/series/977317/",
    "status": "Завершён"
  },
  {
    "id": 113,
    "title": "Jessica Jones",
    "titleRu": "Джессика Джонс",
    "year": 2015,
    "endYear": 2019,
    "seasons": 3,
    "episodes": 39,
    "genres": [
      "Криминал",
      "Драма",
      "Фантастика",
      "Триллер"
    ],
    "country": "США",
    "imdbRating": 7.9,
    "kpRating": 7.6,
    "avgRating": 7.8,
    "description": "Бывшая супергероиня, страдающая от посттравматического синдрома, открывает детективное агентство. Она расследует дела, в которых замешаны люди с необычными способностями.",
    "poster": "https://image.tmdb.org/t/p/w500/7K54OG3m8AJCC9yUCOc4DHG3kmw.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt2364582/",
    "kpUrl": "https://www.kinopoisk.ru/series/820711/",
    "status": "Завершён"
  },
  {
    "id": 114,
    "title": "Loki",
    "titleRu": "Локи",
    "year": 2021,
    "endYear": null,
    "seasons": 2,
    "episodes": 12,
    "genres": [
      "Фэнтези",
      "Фантастика",
      "Боевик",
      "Приключения"
    ],
    "country": "США",
    "imdbRating": 8.2,
    "kpRating": 7.7,
    "avgRating": 8,
    "description": "Бог хитрости Локи попадает в таинственную организацию, управляющую временными линиями. Ему предстоит исправить свои ошибки и разобраться с мультивселенной.",
    "poster": "https://image.tmdb.org/t/p/w500/2GeZ9QrjySwQYG6StjCuC6bTjGl.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt9140554/",
    "kpUrl": "https://www.kinopoisk.ru/series/1202867/",
    "status": "Выходит"
  },
  {
    "id": 115,
    "title": "WandaVision",
    "titleRu": "Ванда/Вижн",
    "year": 2021,
    "endYear": 2021,
    "seasons": 1,
    "episodes": 9,
    "genres": [
      "Фантастика",
      "Фэнтези",
      "Боевик",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 7.9,
    "kpRating": 7.5,
    "avgRating": 7.7,
    "description": "Ванда Максимофф и Вижн живут идеальной пригородной жизнью, стилизованной под классические ситкомы. Но вскоре они начинают подозревать, что все не так, как кажется.",
    "poster": "https://image.tmdb.org/t/p/w500/5M5f2qGojFc6eCSXs9FITA5jF8f.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt9140560/",
    "kpUrl": "https://www.kinopoisk.ru/series/1202871/",
    "status": "Завершён"
  },
  {
    "id": 116,
    "title": "The Falcon and the Winter Soldier",
    "titleRu": "Сокол и Зимний Солдат",
    "year": 2021,
    "endYear": 2021,
    "seasons": 1,
    "episodes": 6,
    "genres": [
      "Боевик",
      "Фантастика",
      "Драма"
    ],
    "country": "США",
    "imdbRating": 7.1,
    "kpRating": 7,
    "avgRating": 7.1,
    "description": "После событий Мстители: Финал Сэм Уилсон и Баки Барнс объединяются, чтобы противостоять новой угрозе и разобраться с наследием Капитана Америки.",
    "poster": "https://image.tmdb.org/t/p/w500/bWQjS9sPZ4H9KMGEPgF0yhrrT9C.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt9015488/",
    "kpUrl": "https://www.kinopoisk.ru/series/1199775/",
    "status": "Завершён"
  },
  {
    "id": 117,
    "title": "Hawkeye",
    "titleRu": "Соколиный глаз",
    "year": 2021,
    "endYear": 2021,
    "seasons": 1,
    "episodes": 6,
    "genres": [
      "Боевик",
      "Криминал",
      "Фантастика"
    ],
    "country": "США",
    "imdbRating": 7.5,
    "kpRating": 7.1,
    "avgRating": 7.3,
    "description": "Клинт Бартон объединяется с молодой лучницей Кейт Бишоп, чтобы разобраться с врагами из своего прошлого и успеть домой к Рождеству.",
    "poster": "https://image.tmdb.org/t/p/w500/hniUUxofvpNdqThmPpVbLXVlff.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt10160804/",
    "kpUrl": "https://www.kinopoisk.ru/series/1262886/",
    "status": "Завершён"
  },
  {
    "id": 118,
    "title": "Moon Knight",
    "titleRu": "Лунный рыцарь",
    "year": 2022,
    "endYear": 2022,
    "seasons": 1,
    "episodes": 6,
    "genres": [
      "Фэнтези",
      "Боевик",
      "Приключения"
    ],
    "country": "США",
    "imdbRating": 7.3,
    "kpRating": 7.2,
    "avgRating": 7.3,
    "description": "Скромный работник сувенирного магазина обнаруживает у себя диссоциативное расстройство идентичности. Он делит тело с наёмником и втягивается в смертельную тайну египетских богов.",
    "poster": "https://image.tmdb.org/t/p/w500/nwEVXH05W49gbiry9edl2vDMU1g.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt10234724/",
    "kpUrl": "https://www.kinopoisk.ru/series/1294119/",
    "status": "Завершён"
  },
  {
    "id": 119,
    "title": "Billions",
    "titleRu": "Миллиарды",
    "year": 2016,
    "endYear": 2023,
    "seasons": 7,
    "episodes": 84,
    "genres": [
      "Драма"
    ],
    "country": "США",
    "imdbRating": 8.3,
    "kpRating": 8.2,
    "avgRating": 8.3,
    "description": "Интеллектуальное противостояние между амбициозным финансовым гением Бобби Аксельродом и принципиальным федеральным прокурором Чаком Роадсом.",
    "poster": "https://image.tmdb.org/t/p/w500/pINLa96k3qbShPwjq6vivhYoSx3.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt4270492/",
    "kpUrl": "https://www.kinopoisk.ru/series/871804/",
    "status": "Завершён"
  },
  {
    "id": 120,
    "title": "Peacemaker",
    "titleRu": "Миротворец",
    "year": 2022,
    "endYear": null,
    "seasons": 1,
    "episodes": 8,
    "genres": [
      "Боевик",
      "Комедия",
      "Фантастика"
    ],
    "country": "США",
    "imdbRating": 8.3,
    "kpRating": 8.1,
    "avgRating": 8.2,
    "description": "Амбициозный патриот, готовый добиваться мира любой ценой, присоединяется к специальной оперативной группе, чтобы устранить новую глобальную угрозу.",
    "poster": "https://image.tmdb.org/t/p/w500/seuVs7Swm0LLAlrsSI9KRti8ttX.jpg",
    "imdbUrl": "https://www.imdb.com/title/tt13146488/",
    "kpUrl": "https://www.kinopoisk.ru/series/1429983/",
    "status": "Выходит"
  }
];
